// <auto-generated />
using Cavavin.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cavavin.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260212113252_SeedInitialData")]
    partial class SeedInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cavavin.API.Models.WineBottle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("domain");

                    b.Property<int>("EndMaturity")
                        .HasColumnType("integer")
                        .HasColumnName("end_maturity");

                    b.Property<string>("FoodPairingKeywords")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("food_pairing_keywords");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("boolean")
                        .HasColumnName("is_favorite");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.Property<int>("StartMaturity")
                        .HasColumnType("integer")
                        .HasColumnName("start_maturity");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<int>("Vintage")
                        .HasColumnType("integer")
                        .HasColumnName("vintage");

                    b.HasKey("Id");

                    b.ToTable("wine_bottles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Domain = "Chateau Margaux",
                            EndMaturity = 2050,
                            FoodPairingKeywords = "agneau,gibier,boeuf",
                            IsFavorite = true,
                            Name = "Chateau Margaux",
                            Quantity = 3,
                            Region = "bordeaux",
                            StartMaturity = 2025,
                            Type = "red",
                            Vintage = 2015
                        },
                        new
                        {
                            Id = 2,
                            Domain = "Mailly Grand Cru",
                            EndMaturity = 2035,
                            FoodPairingKeywords = "aperitif,huitres,crevettes",
                            IsFavorite = false,
                            Name = "Cuvee des Enchanteleurs",
                            Quantity = 6,
                            Region = "champagne",
                            StartMaturity = 2020,
                            Type = "sparkling",
                            Vintage = 2012
                        },
                        new
                        {
                            Id = 3,
                            Domain = "Henri Bourgeois",
                            EndMaturity = 2028,
                            FoodPairingKeywords = "poisson,chevre,volaille",
                            IsFavorite = true,
                            Name = "Sancerre d'Antan",
                            Quantity = 4,
                            Region = "loire",
                            StartMaturity = 2023,
                            Type = "white",
                            Vintage = 2021
                        },
                        new
                        {
                            Id = 4,
                            Domain = "E. Guigal",
                            EndMaturity = 2045,
                            FoodPairingKeywords = "viande rouge,agneau,truffes",
                            IsFavorite = true,
                            Name = "Cote Rotie La Mouline",
                            Quantity = 2,
                            Region = "rhone",
                            StartMaturity = 2026,
                            Type = "red",
                            Vintage = 2018
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
